# Generated by Django 5.2.1 on 2025-05-19 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chat_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", models.TextField()),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("llm", "LLM"),
                            ("strategist", "Marketing Strategist"),
                            ("material_creator", "Material Creator"),
                            ("analyzer", "Social Media Analyzer"),
                            ("post_replier", "Post Replier"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("shared_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("creator_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.post",
                    ),
                ),
            ],
        ),
    ]
